all:
  hosts:
    router:
      ansible_host: 192.168.250.2
      ansible_user: root
      ansible_python_interpreter: "/usr/bin/python3"
  children:
    vps:
      hosts:
        mnl_cloudsigma_vps:
          ansible_host: 116.93.120.110
          ansible_port: 65222
          ansible_user: root
          ansible_python_interpreter: "/usr/bin/python3"
        mnl2_cloudsigma_vps:
          ansible_host: 120.89.61.236
          ansible_port: 65222
          ansible_user: root
          ansible_python_interpreter: "/usr/bin/python3"
