---
# Source: https://github.com/czerwonk/ping_exporter
- name: Create config dir
  ansible.builtin.file:
    path: "{{ ping_exporter_isps_config_path }}"
    state: directory
    mode: "0755"
  loop: "{{ isps | dict2items }}"

- name: Template isp config
  template:
    src: config.yml.j2
    dest: "{{ ping_exporter_isps_config_path }}/config.yml"
  loop: "{{ isps | dict2items }}"

- name: Create isp container/s
  community.general.docker_container:
    name: "ping-exporter-isps-{{ item.key }}"
    image: czerwonk/ping_exporter
    container_default_behavior: compatibility
    comparisons:
      "*": strict
    recreate: yes
    restart_policy: unless-stopped
    restart: yes
    networks_cli_compatible: yes
    purge_networks: yes
    network_mode: macvlan-net
    networks:
      - name: macvlan-net
        ipv4_address: "{{ item.value }}.4"
        links:
          - "ping-exporter-{{ item.key }}"
    volumes:
      - "{{ ping_exporter_isps_config_path }}:/config"
    published_ports:
      - 9427:9427
  loop: "{{ isps | dict2items }}"
