---
# source: https://github.com/billimek/prometheus-speedtest-exporter
- name: Create base container
  community.general.docker_container:
    name: speedtest-exporter
    image: billimek/prometheus-speedtest-exporter:1.1.0
    container_default_behavior: compatibility
    comparisons:
      "*": strict
    recreate: yes
    restart_policy: unless-stopped
    restart: yes
    published_ports:
      - 9469:9469
    dns_servers:
      - 8.8.4.4
      - 8.8.8.8
