---
# source: https://github.com/billimek/prometheus-speedtest-exporter

- name: Log into DockerHub
  community.general.docker_login:
    username: zang3tsu
    password: A89*TvXxQQssAdmV!&HJ

- name: Create isp container/s
  community.general.docker_container:
    name: "speedtest-exporter-{{ item.key }}"
    image: zang3tsu/prometheus-speedtest-exporter
    container_default_behavior: compatibility
    comparisons:
      "*": strict
    recreate: yes
    restart_policy: unless-stopped
    restart: yes
    published_ports:
      - 9469:9469
    dns_servers:
      - 8.8.4.4
      - 8.8.8.8
    networks_cli_compatible: yes
    purge_networks: yes
    network_mode: macvlan-net
    networks:
      - name: macvlan-net
        ipv4_address: "{{ item.value }}.23"
        links:
          - "speedtest-exporter-{{ item.key }}"

  loop: "{{ isps | dict2items }}"
