---
grafana_logs_dir: "{{ base_path }}/grafana/logs"
grafana_data_dir: "{{ base_path }}/grafana/data"
grafana_security:
  admin_user: admin
  admin_password: "{{ grafana_admin_password }}"
grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: "http://{{ prometheus_grafana_web_listen_address }}"
    basicAuth: false
    isDefault: true
grafana_auth:
  anonymous:
    enabled: true
    org_name: Main Org.
    org_role: Viewer
