{
 "title": "ISP Status (Full)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "env", "label": "env", "query": { "query": "label_values(env)" } }
  ]
 },
 "panels": [
  {
   "title": "Download/Upload ($env)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "repeat": "env",
   "yaxes": [
    { "format": "bps", "label": "Speed" }
   ],
   "targets": [
    {
     "expr": "speedtest_download_bytes{env=\"$env\"}*8",
     "legendFormat": "Download"
    },
    {
     "expr": "speedtest_upload_bytes{env=\"$env\"}*8",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Jitter/Latency ($env)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "repeat": "env",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "speedtest_jittter_seconds{env=\"$env\"}",
     "legendFormat": "Jitter"
    },
    {
     "expr": "speedtest_latency_seconds{env=\"$env\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "ICMP round trip time ($env)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "repeat": "env",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms", "label": "RTT" }
   ],
   "targets": [
    {
     "expr": "ping_rtt_mean_seconds{env=\"$env\", ip_version=\"4\"} * 1000",
     "legendFormat": "{{ target }}"
    },
    {
     "expr": "avg (ping_rtt_mean_seconds{env=\"$env\", ip_version=\"4\"}) * 1000",
     "legendFormat": "Average RTT"
    }
   ]
  },
  {
   "title": "ICMP packet loss ($env)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "repeat": "env",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "packet loss" }
   ],
   "targets": [
    {
     "expr": "ping_loss_ratio{env=\"$env\",ip_version=\"4\"}",
     "legendFormat": "{{ target }}"
    },
    {
     "expr": "avg (ping_loss_ratio{env=\"$env\",ip_version=\"4\"})",
     "legendFormat": "Packet Loss"
    }
   ]
  }
 ]
}