---
prometheus_version: latest
prometheus_config_dir: "{{ base_path }}/prometheus/config"
prometheus_db_dir: "{{ base_path }}/prometheus/db"
prometheus_storage_retention: "365d"
prometheus_web_listen_address: "0.0.0.0:9091"
prometheus_web_external_url: "http://{{ ansible_host }}:9091"
prometheus_targets:
  node:
    - targets:
        - "localhost:9091" # prometheus
        - "localhost:9427" # ping_exporter
      labels:
        env: router
prometheus_scrape_jobs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - "localhost:9091"
  - job_name: 'ping_exporter'
    metrics_path: /metrics
    static_configs:
      - targets:
          - "localhost:9427"