---
# Source: https://github.com/czerwonk/ping_exporter
- name: Copy base config
  copy:
    src: config.yml
    dest: "{{ ping_exporter_config_path }}"

- name: Create base container
  community.general.docker_container:
    name: ping-exporter-tracker
    image: czerwonk/ping_exporter
    container_default_behavior: compatibility
    restart_policy: unless-stopped
    restart: yes
    volumes:
      - "{{ ping_exporter_config_path }}:/config"
    published_ports:
      - 9427:9427
