---
# Source: https://github.com/czerwonk/ping_exporter
- name: Copy config
  copy:
    src: config.yml
    dest: "{{ ping_exporter_config_path }}"

- name: Create container for pinging devices
  community.general.docker_container:
    name: ping-exporter-devices
    image: czerwonk/ping_exporter
    container_default_behavior: compatibility
    restart_policy: unless-stopped
    volumes:
      - "{{ ping_exporter_config_path }}:/config"
    published_ports:
      - 9428:9427
